### ISSUE TITLE
error message on deleting bookings

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking#176]
_via mail_

ich habe heute Version 0.9.4 installiert und aktiviert
Beim Testen gab es diese Fehlermeldung beim manuellen Löschen einer Buchung als Admin:
![hpnakdccbhcgcgcm](https://user-images.githubusercontent.com/4009931/48365084-28509a80-e6aa-11e8-89b6-2f83ec0a5b1e.png)

(ich habe in der Liste "Buchungen" auf "Löschen" gedrückt)

**Comment by sgrubsmyon** [comment]
I cannot confirm this. The error complains about only one argument to `$wpdb->prepare()` (here: https://github.com/wielebenwir/commons-booking/blob/master/admin/cb-bookings/class-cb-bookings-table.php#L208), but two expected. But I don't understand why two might be expected. Similar to `sprintf()`, as many arguments after the first are expected as there are items like `%s` or `%d` in the first argument (the query). But the query has no `%s` or `%d`. And in my installation, that error is not thrown. So, there must be special conditions that cause the error that we do not know about.

For me, the error does not occur. Also adding a similar statement

```
print_r($wpdb->get_results($wpdb->prepare("SELECT NOW()")));
```

after line 211 (also only one argument to `prepare()`) does not create any error.

Maybe this is caused by a different (older?) PHP version? I am running PHP version 7.0.33.

**Comment by sgrubsmyon** [comment]
I removed the unnecessary `prepare()`, just in case (https://github.com/sgrubsmyon/commons-booking/commit/c628b5e4e1947e22edb7c8ce9a000cd8d737af20). This should fix the issue.
