### ISSUE TITLE
Lost Password Link not working on WP 5.3

### ISSUE THREAD

**Issue by mega-stoffel** [wielebenwir/commons-booking#179]
There's an issue with the "send lost password link" in combination with the booking plugin.
We're running WP 5.3.
When I have the booking-plugin activated, this link is NOT send. After I enter my username I get redirected to the start page, but there's no confirmation about the sending of that lost-password-link.
When the plugin is de-activated, after I enter my username I get the confirmation, that the link is send out and shortly after I have in in my inbox.
Is this behavior already known? Any hints?

**Comment by flegfleg** [comment]
Hm, could be connected to the login page setting (see screenshot). Can you check if that happens with this setting of? 

<img width="736" alt="Bildschirmfoto 2019-11-29 um 12 40 54" src="https://user-images.githubusercontent.com/4009931/69866912-a677e300-12a5-11ea-88bf-8d14c5608f3a.png">


Will try to reproduce the error next week.

Best

**Comment by mega-stoffel** [comment]
yes, that helps. Thanks a lot! :-)
Now everything works as expected again.

**Comment by nelarsen** [comment]
To me, it looks like the referenced commit https://github.com/wielebenwir/commons-booking/commit/3b74d7aa2ae1e2b4bdb69c6b5109796fbbc99c05 introduced a broken syntax. 
I believe it should be
`add_action( 'profile_update', array( $this->users, 'cb_user_profile_redirect'), 12 );`
rather than
`add_action( 'profile_update', array( $this->users, 'cb_user_profile_redirect', 12) );`

What is the point of a custom commonsbooking-redirect to the start page anyway? I think the Wordpress standard (giving to user some feedback) is better.

Anyway for Frieda & Friedrich, I'll drop the redirect.

Hint: The hook profile_update is called in three unlike cases ([see here](https://wordpress.stackexchange.com/questions/210901/how-to-distinguish-on-hook-profile-update-user-registering-user-resetting-passw)). All of them should be tested for user experience when making changes.
